[project]
name = "branch-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["httpx>=0.28.1", "textual>=6.10.0"]

[project.scripts]
branch-tui = "branch_tui.app:run"

[tool.uv]
package = true

[tool.setuptools.package-data]
"branch_tui" = ["*.tcss"]
